export const ActionTypes = {
    SET_STEPS: 'STEPPER/SET_STEPS',
    SET_STEP: 'STEPPER/SET_STEP',
    INCREMENT_CURRENT_STEP: 'STEPPER/INCREMENT_CURRENT_STEP',
    DECREMENT_CURRENT_STEP: 'DECREMENT_CURRENT_STEP'
}